version: "3.8"

services: 

  nginx:
    build: ./docker/nginx
    container_name: nginx
    tty: true
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - api
    links:
      - api
    networks:
      - default
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  api:
    build: ./docker/php
    container_name: api
    tty: true
    volumes:
        - ./:/var/www
    depends_on:
      - db
    links:
      - db
    networks:
      - default
    volumes:
      - ./:/var/www

  db:
    build: ./docker/mysql
    container_name: db
    tty: true
    ports:
      - '3307:3306'
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    networks:
      - default
   
networks:
  default:
    driver: bridge

volumes:
  dbdata:
    driver: local